/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import app.CommandPattern.Invoker;
import app.CommandPattern.Pages;

/**
 *
 * @author Mannulus
 */
public class Body extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Body() {
        initComponents();
        Invoker.Layouts.add(new Pages("inicio", Body.home1));
        Invoker.Layouts.add(new Pages("est", Body.estadisticas1));
        Invoker.Layouts.add(new Pages("Huser", Body.jHomeuser1));
        Invoker.Layouts.add(new Pages("chat", Body.jChat1));
        Invoker.Layouts.add(new Pages("Hpro", Body.jhomepro1));
        /*home1.ingresar_click = (new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1.setVisible(false);
            }
        });*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home1 = new Frames.Home();
        estadisticas1 = new Frames.Estadisticas();
        jChat1 = new Frames.JChat();
        jHomeuser1 = new Frames.JHomeuser();
        jhomepro1 = new Frames.Jhomepro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GOOD MIND");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(estadisticas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jChat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jHomeuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jhomepro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static Frames.Estadisticas estadisticas1;
    public static Frames.Home home1;
    private static Frames.JChat jChat1;
    private static Frames.JHomeuser jHomeuser1;
    public static Frames.Jhomepro jhomepro1;
    // End of variables declaration//GEN-END:variables
}
