/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import app.Goodmind;
import app.Mensaje;
import app.TypeMenssage;
import javax.swing.plaf.basic.BasicHTML;
import javax.swing.text.View;

/**
 *
 * @author Mannulus
 */
public class JBurbujaChat extends javax.swing.JPanel {

    /**
     * Creates new form JBurbujaChat
     */
    public JBurbujaChat() {
        initComponents();
    }

    public JBurbujaChat(Mensaje msj) {
        initComponents();
        this.setTypeChat(msj);
    }

    public void setTypeChat(Mensaje msj) {
        Texto.setText(msj.mensaje);
        if (msj.id_remitente.equals(Goodmind.user.id)) {
            Texto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            add(new Avatar("/Images/chat_right.png", 305, 65));
        } else {
            Texto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            add(new Avatar("/Images/chat_left.png", 305, 65));
        }

        /*switch (msj.tipo) {
            case text:
                iconvoice.setVisible(false);
                jSeparator1.setVisible(false);
                panelVoice.setVisible(false);
                break;
            case emocion:
                //iconvoice.setVisible(false);
                iconvoice.add(new Avatar("/Images/"+msj.mensaje+".png",60,60));
                Texto.setVisible(false);
                jSeparator1.setVisible(false);
                break;
            case voice:
                iconvoice.add(new Avatar("/Images/play_icon.png",60,60));
                Texto.setVisible(false);
                break;
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(324, 65));
        setMinimumSize(new java.awt.Dimension(324, 65));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(324, 65));

        Texto.setFont(new java.awt.Font("Sitka Small", 0, 13)); // NOI18N
        Texto.setText("el texto va aqui escritoasjdfjasdjfjasdjfjas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Texto;
    // End of variables declaration//GEN-END:variables

}
