/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import app.CommandPattern.Invoker;
import app.Conversacion;
import app.Goodmind;
import app.TypeMenssage;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author Mannulus
 */
public class JChat extends javax.swing.JPanel {

    /**
     * Creates new form JChat
     */
    public JChat() {
        initComponents();
        
        DefaultListModel model = new DefaultListModel();
        JBurbujaChat pane = new JBurbujaChat();
        pane.setTypeChat(TypeMenssage.text);
        model.addElement(pane);
        JList<JPanel > lista = new JList();
        lista.setModel(model);
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setCellRenderer(new PanelRenderer());
        jScrollPane2.setViewportView(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel1.setText("nombre usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 17, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 597, 211, 51));

        jButton2.setText("estadistica");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 90, 50));

        jButton3.setText("jButton2");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 70, 50));
        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 310, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Invoker.ChangePanel("Huser");
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
