/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import app.CommandPattern.Invoker;
import app.Conversacion;
import app.Goodmind;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Mannulus
 */
public class Jhomepro extends javax.swing.JPanel {

    /**
     * Creates new form Jhomepro
     */
    public Jhomepro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        togglechat = new javax.swing.JToggleButton();
        togglebaul = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JPanel();
        jContacto1 = new Frames.JContacto();

        setBackground(new java.awt.Color(204, 255, 255));

        togglechat.setBackground(new java.awt.Color(204, 255, 255));
        togglechat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chat_icon.png"))); // NOI18N
        togglechat.setSelected(true);
        togglechat.setBorder(null);
        togglechat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglechatActionPerformed(evt);
            }
        });

        togglebaul.setBackground(new java.awt.Color(204, 255, 255));
        togglebaul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baul_icon.png"))); // NOI18N
        togglebaul.setBorder(null);
        togglebaul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglebaulActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout_icon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/good_text.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CHAT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("BAÚL");

        jList1.setLayout(new javax.swing.BoxLayout(jList1, javax.swing.BoxLayout.PAGE_AXIS));
        jList1.add(jContacto1);

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(togglechat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(togglebaul, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(togglechat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(togglebaul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Invoker.ChangePanel("inicio");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void togglechatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglechatActionPerformed
        setBaul(false);
    }//GEN-LAST:event_togglechatActionPerformed

    private void togglebaulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglebaulActionPerformed
        setBaul(true);
    }//GEN-LAST:event_togglebaulActionPerformed
    @Override
    public void setVisible(boolean v) {
        if (v) {
            setChats();
        }
        super.setVisible(v);
    }

    public void setChats() {
        jList1.removeAll();
        if (Goodmind.user == null) {
            return;
        }
        //model.clear();
        //JPanel[] jpanels = new JPanel[Goodmind.user.conversaciones.size()];

        for (Conversacion chat : Goodmind.user.conversaciones) {
            if (baul) {
                if (!chat.activo) {
                    JContacto pane = new JContacto();
                    pane.name.setText(chat.ChatUser);
                    pane.name_user = chat.ChatUser;
                    pane.icon_active.setVisible(false);
                    jList1.add(pane);
                }
            } else {
                if (chat.activo) {
                    JContacto pane = new JContacto();
                    pane.name.setText(chat.ChatUser);
                    pane.name_user = chat.ChatUser;
                    pane.icon_active.setVisible(true);
                    jList1.add(pane);
                }
            }
        }
        jList1.repaint();
        jList1.validate();

        //int row = i < 5 ? 5 : i;
        //jList1.setLayout(new java.awt.GridLayout(row, 1));
        /*JList<JPanel> lista = new JList();
        lista.setModel(model);
        lista.setListData(jpanels);*/
        //lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        //lista.setCellRenderer(new PanelRenderer());
        //jScrollPane1.setViewportView(lista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private Frames.JContacto jContacto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton togglebaul;
    private javax.swing.JToggleButton togglechat;
    // End of variables declaration//GEN-END:variables
    DefaultListModel model = new DefaultListModel();
    private boolean baul = false;

    public void setBaul(boolean val) {
        baul = val;
        togglebaul.setSelected(val);
        togglechat.setSelected(!val);
        setChats();//actuliza la lista
    }
}

class PanelRenderer implements ListCellRenderer {

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JPanel renderer = (JPanel) value;
        renderer.setBackground(isSelected ? new Color(0, 204, 255) : list.getBackground());//renderer.getBackground()
        return renderer;
    }
}
